### ISSUE TITLE
Pretraining VL models

### ISSUE THREAD

**Issue by zoranadozdor** [thearkaprava/SKI-Models#2]
For the pretraining of VL models, are they trained only on Kinetics-400 before SkeletonCLIP distillation, or are they also pretrained on seen classes of NTU? If they are, could you provide details such as the number of epochs, whether the text encoder is frozen, etc.?

**Comment by thearkaprava** [comment]
Hi @zoranadozdor, thank you for your interest.

The Vision Language (VL) models have been pretrained only on the seen classes of NTU for each split. All parameters of the VL models are trainable in this stage for effective video-language alignment. 

For ViFiCLIP, the following config was used:

```
DATA:
    DATASET: ntu60 #or ntu120
    INPUT_SIZE: 224
    LABEL_LIST: /path/to/Base_class_labels.csv 
    NUM_CLASSES: <Number of Seen classes>
    NUM_FRAMES: 16
    ROOT: /path/to/ntu/NTU60_224x224/rgb
    TRAIN_FILE: /path/to/ntu/Base_train_data.csv 
    VAL_FILE: /path/to/ntu/Base_val_data.csv 

SAVE_FREQ: 10
MODEL:
    ARCH: ViT-B/16

TRAIN:
    EPOCHS: 20
    BATCH_SIZE: 4 #  (Effective Batch-size=64)
    ACCUMULATION_STEPS: 16  # for 8 gpus this should be 16
    LR: 2.2e-05 
    WARMUP_EPOCHS: 5 
TEST:
    MULTI_VIEW_INFERENCE: False # By default in ViFi-Clip this is set to true
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
```

For XCLIP and FROSTER, we following their training configurations.
